version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/hack/kind"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/hack/kubernetes"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
